@startuml

title 模块结构图

[order-service] ---> [order-create]
[order-service] ---> [order-select]
[order-service] ---> [order-select-slow]

[order-dao] <-- [order-create]
[order-dao] <-- [order-select]
[order-dao] <-- [order-select-slow]

@enduml